### ISSUE TITLE
AttributeError during training

### ISSUE THREAD

**Issue by wanzhouliu** [GaTech-RL2/nvf_cvpr24#3]
**Describe the bug**
Hi, thank you for your timely response! I rebuilt the environment but got the following error during training. Seems there are some small issues with the published code?

**To Reproduce**
python eval.py --scene hubble --method nvf

**Additional context**
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled tensorboard/wandb event writers
Starts extracting mesh
Ends extracting mesh
Generating data for eval
 40%|█████████████████████████████▌                                            | 8/20 [00:33<00:55,  4.59s/it]Exception in thread Thread-4:
Traceback (most recent call last):
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/viewer/server/render_state_machine.py", line 173, in run
    outputs = self._render_img(action.cam_msg)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/viewer/server/render_state_machine.py", line 148, in _render_img
    outputs = self.viewer.get_model().get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/models/base_model.py", line 179, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/models/instant_ngp.py", line 309, in get_outputs
    field_outputs = self.field(ray_samples)
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/fields/base_field.py", line 124, in forward
    density, density_embedding = self.get_density(ray_samples)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/fields/nerfacto_field.py", line 252, in get_density
    h = self.mlp_base(positions_flat).view(*ray_samples.frustums.shape, -1)
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/field_components/mlp.py", line 178, in forward
    return self.pytorch_fwd(in_tensor)
  File "/data2/wanzhou/nvf_cvpr24/nerfstudio/field_components/mlp.py", line 164, in pytorch_fwd
    for i, layer in enumerate(self.layers):
  File "/data2/wanzhou/miniforge3/envs/nvf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MLP' object has no attribute 'layers'
100%|█████████████████████████████████████████████████████████████████████████| 20/20 [01:23<00:00,  4.17s/it]
saving data to data/hubble/eval/transforms.json
Traceback (most recent call last):
  File "/data2/wanzhou/nvf_cvpr24/eval.py", line 452, in <module>
    multi_evaluation(cfg)
  File "/data2/wanzhou/nvf_cvpr24/eval.py", line 360, in multi_evaluation
    result = evaluate(cfg, i)
  File "/data2/wanzhou/nvf_cvpr24/eval.py", line 279, in evaluate
    tracker = RefMetricTracker(cfg, env=env)
  File "/data2/wanzhou/nvf_cvpr24/nvf/metric/MetricTracker.py", line 62, in __init__
    self.visibility_metric = VisibilityMeshMetric(scene=env.scene)
  File "/data2/wanzhou/nvf_cvpr24/nvf/metric/mesh_metrics.py", line 69, in __init__
    vertices = torch.tensor(mesh.vertices, dtype=torch.float32).to(self.device)
AttributeError: 'Scene' object has no attribute 'vertices'

**Comment by JesseDill** [comment]
For extracting a mesh from the scene, we typically use trimesh. But for the Hubble environment asset, we extracted the mesh directly from blender. This worked fine when performing our experiments, but it looks like I'm now getting the same error on my end. It's not clear to me what changed either in dependencies or the code base that caused this. For now I changed the Hubble mesh to be extracted with trimesh. You should be able to train NVF and see the results on the Hubble environment in the latest version of the repo.

That error you see doesn't happen for training NVF on other scenes such as hotdog, room, lego. Just make sure to attach the [assets](https://drive.google.com/drive/folders/1s2g-gBiHMOdQTVtmuTLGfcaA7OMJazvt) into /data/assets/blend_files/
